### ISSUE TITLE
index.js switch문 변경 관련

### ISSUE THREAD

**Issue by zkf1233** [hellemon/OSS_tutorial_project#22]
![image](https://user-images.githubusercontent.com/40075034/205478662-3d194340-5e8d-4cb9-b1a5-1abaf7024a99.png)

텍스트가 정규식에 맞는지 보기 위해 switch문을 수정하였는데, 

switch문 내에서는 변수 선언이 안되어서 일단 밖에 if문으로 학과 정보사용만 따로 빼어 사용하고 pr하겠습니다.

**Comment by hellemon** [comment]
넵 알겠습니다

**Comment by yanggyuheon** [comment]
네 확인했습니다
