### ISSUE TITLE
feature 3에서 발생하는 문제가 있습니다.

### ISSUE THREAD

**Issue by hellemon** [hellemon/OSS_tutorial_project#25]
문제 상황 : nodejs index.js를 하게 될 경우
![image](https://user-images.githubusercontent.com/94850119/205481947-147a3823-7205-4fd5-b583-129d1edee4e8.png)
와 같은 문제가 발생하게 되는데 이 부분에 대해서 혹시 저만 문제가 발생하였나요?
된다면 해결 방법은 무엇이였나요?

**Comment by yanggyuheon** [comment]
node --experimental-modules index.js
이러한 방식의 코드로 진행하게 되면 index.js가 버그없이 해결됩니다
