### ISSUE TITLE
index.js switch문 변경 관련

### ISSUE THREAD

**Issue by yanggyuheon** [hellemon/OSS_tutorial_project#28]
기존 switch문 방식 바꿔보았습니다.
어느 방식이 좋은지 말해주세요

-기존
![3](https://user-images.githubusercontent.com/112867282/206466129-dba9ca97-d78f-4ce8-886d-2ab8604433e0.png)

-수정
![1](https://user-images.githubusercontent.com/112867282/206465550-9f216b9e-fa68-4336-8785-d7984f1dfc48.png)

**Comment by hellemon** [comment]
if문으로 저런식으로 맨 처음에 학과 사무실 정보를 만든건 아마 저일텐데 현재 switch문으로 하신게 코드를 유지보수하는 측면에서 더 좋은것 같기도 합니다. 통일성이 있는것 같아서 저는 괜찮다고 생각해요

**Comment by yanggyuheon** [comment]
민식님 switch-case 방식 PR로 수정
