### ISSUE TITLE
feature4 spawn관련 이슈

### ISSUE THREAD

**Issue by zkf1233** [hellemon/OSS_tutorial_project#30]
![image](https://user-images.githubusercontent.com/40075034/206590538-29e92ef6-586c-4270-9ede-f9268fe7c4b2.png)

규헌님께서 올려주신 코드 바탕으로 작성시 저와 규헌님 환경이 windows이기 때문에 spawn에 첫 인자로 "py"를 줘야 실행이 되는데,

![image](https://user-images.githubusercontent.com/40075034/206590470-d9ade01b-ba99-4e64-bba8-61ab512ec669.png)

깃허브에 올릴때 mocha테스트 환경을 ubuntu로 잡았고, 저희가 올려서 테스트해야할 서버(네이버 무료제공 서버)도 강의시간에 ubuntu로 만들어서 돌리고있기 때문에 인자를 줄때 "python3(설치된 버전에 따라 숫자변경)" 이점 확인하셔야될것 같습니다. 

![image](https://user-images.githubusercontent.com/40075034/206590955-e61b7434-5674-424d-9399-35ea5c976be6.png)

일단 따로 feature4 와 feature3 mocha까지 모두 작업 완료했습니다. 모카 내역은 actions들어가서 확인해보시면 될것 같습니다. 나머지 하나 남은 통합 테스트 봇과, README 작성은 어떻게 할지 알려주시면 감사하겠습니다.

**Comment by hellemon** [comment]
저도 저 부분에서 안되는걸 보고 왜 안되지 하였다가 수정하였었는데 이슈로 올리셨네요 pip3로 해서 하면 되는것 같습니다

**Comment by yanggyuheon** [comment]
PR #33 spawn => pythonshell 방식으로 수정했습니다
