### ISSUE TITLE
feature 4 진행 중 python version이 3 미만인 경우에 대해서

### ISSUE THREAD

**Issue by hellemon** [hellemon/OSS_tutorial_project#32]
문제가 되는 기능 : feature4

문제 상황
jellyfish library가 파이썬 3.6 이상을 지원하는 걸로 알고 있어서 기존에 설치 되어 있던 파이썬 버전 즉 2.xx에서는 동작하지 않습니다.

해결 방안
https://jjeongil.tistory.com/1274
위의 블로그와 같이 하여서 python version을 올려주시면 됩니다.

**Comment by yanggyuheon** [comment]
네 확인했습니다.
